### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by schutm** [asdf-ocaml/asdf-opam#1]
```
./opam-installer --prefix "/home/martin/.asdf/installs/opam/2.0.1" --mandir "/home/martin/.asdf/installs/opam/2.0.1/share/man" --libdir "/usr/local/lib/ocaml/4.05.0" opam-installer.install
_build/install/default/bin/opam-installer => /home/martin/.asdf/installs/opam/2.0.1/bin/opam-installer
Creating directory /usr/local/lib/ocaml/4.05.0/opam-installer
[ERROR] Failure during install
./opam-installer: "mkdir" failed on /usr/local/lib/ocaml/4.05.0/opam-installer: Permission denied
make[1]: *** [Makefile:142: install] Error 1
make[1]: Leaving directory '/tmp/opam_build_4ldbnz/dist'
make: *** [Makefile:195: cold-install] Error 2
```

it seems like the libdir is not correctly passed to the configure script.

As a side note: is there a specific reason the sources are compiled and the compiled releases are not used?

**Comment by imbsky** [comment]
Yes, Opam repository has compiled releases, so we can use it. but this problem is weird.

**Comment by imbsky** [comment]
OK, it should have been fixed by https://github.com/asdf-ocaml/asdf-opam/commit/706d4939c1bcb89a82b4d3e2ab6be7501899544e.

**Comment by schutm** [comment]
Works now.

**Comment by imbsky** [comment]
@all-contributors please add @imbsky for code doc maintenance

**Comment by imbsky** [comment]
@all-contributors please add @schutm for bug
